function autocomplete(inp, arr) {
  /*the autocomplete function takes two arguments,
  the text field element and an array of possible autocompleted values:*/
  var currentFocus;
  /*execute a function when someone writes in the text field:*/
  inp.addEventListener("input", function (e) {
    var a, b, i, val = this.value;
    /*close any already open lists of autocompleted values*/
    closeAllLists();
    if (!val) { return false; }
    currentFocus = -1;
    /*create a DIV element that will contain the items (values):*/
    a = document.createElement("DIV");
    a.setAttribute("id", this.id + "autocomplete-list");
    a.setAttribute("class", "autocomplete-items");
    /*append the DIV element as a child of the autocomplete container:*/
    this.parentNode.appendChild(a);
    /*for each item in the array...*/
    for (i = 0; i < arr.length; i++) {
      /*check if the item starts with the same letters as the text field value:*/
      if (arr[i].substr(0, val.length).toUpperCase() == val.toUpperCase()) {
        /*create a DIV element for each matching element:*/
        b = document.createElement("DIV");
        /*make the matching letters bold:*/
        b.innerHTML = "<strong>" + arr[i].substr(0, val.length) + "</strong>";
        b.innerHTML += arr[i].substr(val.length);
        /*insert a input field that will hold the current array item's value:*/
        b.innerHTML += "<input type='hidden' value='" + arr[i] + "'>";
        /*execute a function when someone clicks on the item value (DIV element):*/
        b.addEventListener("click", function (e) {
          /*insert the value for the autocomplete text field:*/
          inp.value = this.getElementsByTagName("input")[0].value;
          /*close the list of autocompleted values,
          (or any other open lists of autocompleted values:*/
          closeAllLists();
        });
        a.appendChild(b);
      }
    }
  });
  /*execute a function presses a key on the keyboard:*/
  inp.addEventListener("keydown", function (e) {
    var x = document.getElementById(this.id + "autocomplete-list");
    if (x) x = x.getElementsByTagName("div");
    if (e.keyCode == 40) {
      /*If the arrow DOWN key is pressed,
      increase the currentFocus variable:*/
      currentFocus++;
      /*and and make the current item more visible:*/
      addActive(x);
    } else if (e.keyCode == 38) { //up
      /*If the arrow UP key is pressed,
      decrease the currentFocus variable:*/
      currentFocus--;
      /*and and make the current item more visible:*/
      addActive(x);
    } else if (e.keyCode == 13) {
      /*If the ENTER key is pressed, prevent the form from being submitted,*/
      e.preventDefault();
      if (currentFocus > -1) {
        /*and simulate a click on the "active" item:*/
        if (x) x[currentFocus].click();
      }
    }
  });
  function addActive(x) {
    /*a function to classify an item as "active":*/
    if (!x) return false;
    /*start by removing the "active" class on all items:*/
    removeActive(x);
    if (currentFocus >= x.length) currentFocus = 0;
    if (currentFocus < 0) currentFocus = (x.length - 1);
    /*add class "autocomplete-active":*/
    x[currentFocus].classList.add("autocomplete-active");
  }
  function removeActive(x) {
    /*a function to remove the "active" class from all autocomplete items:*/
    for (var i = 0; i < x.length; i++) {
      x[i].classList.remove("autocomplete-active");
    }
  }
  function closeAllLists(elmnt) {
    /*close all autocomplete lists in the document,
    except the one passed as an argument:*/
    var x = document.getElementsByClassName("autocomplete-items");
    for (var i = 0; i < x.length; i++) {
      if (elmnt != x[i] && elmnt != inp) {
        x[i].parentNode.removeChild(x[i]);
      }
    }
  }
  /*execute a function when someone clicks in the document:*/
  document.addEventListener("click", function (e) {
    closeAllLists(e.target);
  });
}

/*An array containing all the country names in the world:*/
var estados = [
  "Buenos Aires",
  "Capital Federal",
  "Catamarca",
  "Chaco",
  "Chubut",
  "Cordoba",
  "Corrientes",
  "Entre Rios",
  "Formosa",
  "Jujuy",
  "La Pampa",
  "La Rioja",
  "Mendoza",
  "Misiones",
  "Neuquen",
  "Rio Negro",
  "Salta",
  "San Juan",
  "San Luis",
  "Santa Cruz",
  "Santa Fe",
  "Santiago del Estero",
  "Tierra del Fuego",
  "Tucuman",
  "Chuquisaca",
  "Cochabamba",
  "Beni",
  "La Paz",
  "Oruro",
  "Pando",
  "Potosi",
  "Santa Cruz",
  "Tarija",
  "Acre",
  "Alagoas",
  "Amapa",
  "Amazonas",
  "Bahia",
  "Ceara",
  "Distrito Federal",
  "Espirito Santo",
  "Goias",
  "Maranhao",
  "Mato Grosso",
  "Mato Grosso do Sul",
  "Minas Gerais",
  "Para",
  "Paraiba",
  "Parana",
  "Pernambuco",
  "Piaui",
  "Rio de Janeiro",
  "Rio Grande do Norte",
  "Rio Grande do Sul",
  "Rondonia",
  "Roraima",
  "Santa Catarina",
  "Sao Paulo",
  "Sergipe",
  "Tocantins",
  "Alberta",
  "British Columbia",
  "Manitoba",
  "New Brunswick",
  "Newfoundland and Labrador",
  "Northwest Territories",
  "Nova Scotia",
  "Nunavut",
  "Ontario",
  "Prince Edward Island",
  "Quebec",
  "Saskatchewan",
  "Yukon Territory",
  "Antofagasta",
  "Araucania",
  "Atacama",
  "Bio-Bio",
  "Coquimbo",
  "Libertador General B",
  "Los Lagos",
  "Magallanes",
  "Maule",
  "Santiago",
  "Tarapaca",
  "Valparaiso",
  "Amazonas",
  "Antioquia",
  "Arauca",
  "Atlantico",
  "Distrito Capital de Bogota",
  "Bolivar",
  "Boyaca",
  "Caldas",
  "Caqueta",
  "Casanare",
  "Cauca",
  "Cesar",
  "Choco",
  "Cordoba",
  "Cundinamarca",
  "Guainia",
  "Guaviare",
  "Huila",
  "La Guajira",
  "Magdalena",
  "Meta",
  "Narino",
  "Norte de Santander",
  "Putumayo",
  "Quindio",
  "Risaralda",
  "San Andres y Providencia",
  "Santander",
  "Sucre",
  "Tolima",
  "Valle del Cauca",
  "Vaupes",
  "Vichada",
  "Alibori",
  "Atakora",
  "Atlantique",
  "Borgou",
  "Collines",
  "Kouffo",
  "Donga",
  "Littoral",
  "Mono",
  "Oueme",
  "Plateau",
  "Zou",
  "Camaguey",
  "Ciego de Avila",
  "Cienfuegos",
  "Ciudad de La Habana",
  "Granma",
  "Guantanamo",
  "Holguin",
  "Isla de la Juventud",
  "La Habana",
  "Las Tunas",
  "Matanzas",
  "Pinar del Rio",
  "Sancti Spiritus",
  "Santiago de Cuba",
  "Villa Clara",
  "Azuay",
  "Bolivar",
  "Canar",
  "Carchi",
  "Chimborazo",
  "Cotopaxi",
  "El Oro",
  "Esmeraldas",
  "Galapagos",
  "Guayas",
  "Imbabura",
  "Loja",
  "Los Rios",
  "Manabi",
  "Morona-Santiago",
  "Napo",
  "Orellana",
  "Pastaza",
  "Pichincha",
  "Sucumbios",
  "Tungurahua",
  "Zamora-Chinchipe",
  "Ahuachapan",
  "Cabanas",
  "Chalatenango",
  "Cuscatlan",
  "La Libertad",
  "La Paz",
  "La Union",
  "Morazan",
  "San Miguel",
  "San Salvador",
  "Santa Ana",
  "San Vicente",
  "Sonsonate",
  "Usulutan",
  "Andalucia",
  "Aragon",
  "Asturias",
  "Baleares",
  "Ceuta",
  "Canarias",
  "Cantabria",
  "Castilla-La Mancha",
  "Castilla y Leon",
  "Cataluña",
  "Comunidad Valenciana",
  "Extremadura",
  "Galicia",
  "La Rioja",
  "Madrid",
  "Melilla",
  "Murcia",
  "Navarra",
  "Pais Vasco",
  "Alabama",
  "Alaska",
  "Arizona",
  "Arkansas",
  "California",
  "Colorado",
  "Connecticut",
  "Delaware",
  "District of Columbia",
  "Florida",
  "Georgia",
  "Hawaii",
  "Idaho",
  "Illinois",
  "Indiana",
  "Iowa",
  "Kansas",
  "Kentucky",
  "Louisiana",
  "Maine",
  "Maryland",
  "Massachusetts",
  "Michigan",
  "Minnesota",
  "Mississippi",
  "Missouri",
  "Montana",
  "Nebraska",
  "Nevada",
  "New Hampshire",
  "New Jersey",
  "New Mexico",
  "New York",
  "North Carolina",
  "North Dakota",
  "Ohio",
  "Oklahoma",
  "Oregon",
  "Pennsylvania",
  "Rhode Island",
  "South Carolina",
  "South Dakota",
  "Tennessee",
  "Texas",
  "Utah",
  "Vermont",
  "Virginia",
  "Washington",
  "West Virginia",
  "Wisconsin",
  "Wyoming",
  "Alta Verapaz",
  "Baja Verapaz",
  "Chimaltenango",
  "Chiquimula",
  "El Progreso",
  "Escuintla",
  "Guatemala",
  "Huehuetenango",
  "Izabal, Jalapa",
  "Jutiapa",
  "Peten",
  "Quetzaltenango",
  "Quiche",
  "Retalhuleu",
  "Sacatepequez",
  "San Marcos",
  "Santa Rosa",
  "Solola",
  "Suchitepequez",
  "Totonicapan",
  "Zacapa",
  "Atlantida",
  "Choluteca",
  "Colon",
  "Comayagua",
  "Copan",
  "Cortes",
  "El Paraiso",
  "Francisco Morazan",
  "Gracias a Dios",
  "Intibuca",
  "Islas de la Bahia",
  "La Paz",
  "Lempira",
  "Ocotepeque",
  "Olancho",
  "Santa Barbara",
  "Valle",
  "Yoro",
  "Aguascalientes",
  "Baja California",
  "Baja California Sur",
  "Campeche",
  "Chiapas",
  "Chihuahua",
  "Coahuila de Zaragoza",
  "Colima",
  "Distrito Federal",
  "Durango",
  "Guanajuato",
  "Guerrero",
  "Hidalgo",
  "Jalisco",
  "Mexico",
  "Michoacan de Ocampo",
  "Morelos",
  "Nayarit",
  "Nuevo Leon",
  "Oaxaca",
  "Puebla",
  "Queretaro de Arteaga",
  "Quintana Roo",
  "San Luis Potosi",
  "Sinaloa",
  "Sonora",
  "Tabasco",
  "Tamaulipas",
  "Tlaxcala",
  "Veracruz-Llave",
  "Yucatan",
  "Zacatecas",
  "Atlantico Norte",
  "Atlantico Sur",
  "Boaco",
  "Carazo",
  "Chinandega",
  "Chontales",
  "Esteli",
  "Granada",
  "Jinotega",
  "Leon",
  "Madriz",
  "Managua",
  "Masaya",
  "Matagalpa",
  "Nueva Segovia",
  "Rio San Juan",
  "Rivas",
  "Bocas del Toro",
  "Chiriqui",
  "Cocle",
  "Colon",
  "Darien",
  "Herrera",
  "Los Santos",
  "Panama",
  "San Blas",
  "Kuna Yala",
  "Veraguas",
  "Alto Paraguay",
  "Alto Parana",
  "Amambay",
  "Asuncion",
  "Boqueron",
  "Caaguazu",
  "Caazapa",
  "Canindeyu",
  "Central",
  "Concepcion",
  "Cordillera",
  "Guaira",
  "Itapua",
  "Misiones",
  "Neembucu",
  "Paraguari",
  "Presidente Hayes",
  "San Pedro",
  "Amazonas",
  "Ancash",
  "Apurimac",
  "Arequipa",
  "Ayacucho",
  "Cajamarca",
  "Callao",
  "Cusco",
  "Huancavelica",
  "Huanuco",
  "Ica",
  "Junin",
  "La Libertad",
  "Lambayeque",
  "Lima",
  "Madre de Dios",
  "Moquegua",
  "Pasco",
  "Piura",
  "Puno",
  "San Martin",
  "Tacna",
  "Tumbes",
  "Ucayali",
  "Adjuntas",
  "Aguada",
  "Aguadilla",
  "Aguas Buenas",
  "Aibonito",
  "Anasco",
  "Arecibo",
  "Arroyo",
  "Barceloneta",
  "Barranquitas",
  "Bayamon",
  "Cabo Rojo",
  "Caguas",
  "Camuy",
  "Canovanas",
  "Carolina",
  "Catano",
  "Cayey",
  "Ceiba",
  "Ciales",
  "Cidra",
  "Coamo",
  "Comerio",
  "Corozal",
  "Culebra",
  "Dorado",
  "Fajardo",
  "Florida",
  "Guanica",
  "Guayama",
  "Guayanilla",
  "Guaynabo",
  "Gurabo",
  "Hatillo",
  "Hormigueros",
  "Humacao",
  "Isabela",
  "Jayuya",
  "Juana Diaz",
  "Juncos",
  "Lajas",
  "Lares",
  "Las Marias",
  "Las Piedras",
  "Loiza",
  "Luquillo",
  "Manati",
  "Maricao",
  "Maunabo",
  "Mayaguez",
  "Moca",
  "Morovis",
  "Naguabo",
  "Naranjito",
  "Orocovis",
  "Patillas",
  "Penuelas",
  "Ponce",
  "Quebradillas",
  "Rincon",
  "Rio Grande",
  "Sabana Grande",
  "Salinas",
  "San German",
  "San Juan",
  "San Lorenzo",
  "San Sebastian",
  "Santa Isabel",
  "Toa Alta",
  "Toa Baja",
  "Trujillo Alto",
  "Utuado",
  "Vega Alta",
  "Vega Baja",
  "Vieques",
  "Villalba",
  "Yabucoa",
  "Yauco",
  "Artigas",
  "Canelones",
  "Cerro Largo",
  "Colonia",
  "Durazno",
  "Flores",
  "Florida",
  "Lavalleja",
  "Maldonado",
  "Montevideo",
  "Paysandu",
  "Rio Negro",
  "Rivera",
  "Rocha",
  "Salto",
  "San Jose",
  "Soriano",
  "Tacuarembo",
  "Treinta y Tres"
];

/*initiate the autocomplete function on the "myInput" element, and pass along the estados array as possible autocomplete values:*/
autocomplete(document.getElementById("estado"), estados);
